production:
  adapter:  postgresql
  host:     localhost
  database: saifas_leans
  username: rspec
  password: "rspec0000"
  encoding: utf8
  schema_search_path: public

development:
  adapter:  postgresql
  host:     localhost
  database: saifas_leans_development
  username: rspec
  password: "rspec0000"
  encoding: utf8
  schema_search_path: public

test:
  adapter:  postgresql
  host:     localhost
  database: saifas_leans_test
  username: rspec
  password: "rspec0000"
  encoding: utf8
  schema_search_path: public
